AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

Metrics/BlockLength:
  AllowedPatterns: ['Script']
Lint/ConstantDefinitionInBlock:
  AllowedMethods: ['Script']
Metrics/MethodLength:
  Max: 25

Lint/ConstantDefinitionInBlock:
  Enabled: false
